- name: CoreOS | Check if bootstrap is needed
  raw: stat {{ bootstrap_script_dir }}/.bootstrapped
  register: need_bootstrap
  ignore_errors: True

- name: CoreOS | Run bootstrap.sh
  script: bootstrap.sh
  environment:
    BOOTSTRAP_SCRIPT_DIR: "{{ bootstrap_script_dir }}"
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
  when: need_bootstrap | failed

- name: CoreOS | Add /opt/bin to PATH for bootstrapping
  copy:
    src=opt-path.sh
    dest=/etc/profile.d/opt-path.sh
    mode=0755 
